image: node

before_script:
  - npm install

stages: # Ici on déclare toutes nos étapes
  - step1
  - step2
  - step3
  - step4

test:unit:
  stage: step1 # On déclare que ce `job` fait partie de l'étape test
  only:
    - main
  script: npm run test:unit

test:coverage:
  only:
      - main
  stage: step1 # On déclare que ce `job` fait partie de l'étape test
  script: npm run test:coverage


lint:
  only:
      - main
  stage: step2
  script: npm run lint

deploy:
  only:
    - main
  stage: step3
  script: echo "deploy script"


result:sucess:
  only:
    - main
  stage: step4
  script: echo "Success"
  when: on_success


result:fail:
  only:
    - main
  stage: step4
  script: echo "Fail"
  when: on_failure