name: Vue.js build and deploy

on:
  push:
    branches:
      - luka

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: echo "🔎 Le pipline commence ici !"

  a:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: echo "Job A fini"

  b:
    runs-on: ubuntu-latest
    needs: a
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: echo "Job B fini"

  c:
    runs-on: ubuntu-latest
    needs: b
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: echo "Job C fini"

  d:
    runs-on: ubuntu-latest
    needs: c
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: echo "Job D fini"

  e:
    runs-on: ubuntu-latest
    needs: d
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: echo "Job E fini"

  f:
    runs-on: ubuntu-latest
    needs: e
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: echo "Job F fini"

  g:
    runs-on: ubuntu-latest
    needs: f
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: echo "Job G fini"

  build:
    runs-on: ubuntu-latest
    needs: g
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 Deployement"
  fin:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo "Fin"
