on:
  push:
    branches:
      - flo3

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: echo "🔎 Le pipline commence ici !"
  test-unit:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm install
      - run: npm run test:unit
      - run: echo "lmao a"
      - run: echo "lmao b"
  test-coverage:
    needs: [init, test-unit]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: echo "im e i guess"
      - run: echo "im f i guess"
  lint:
    needs: [init, test-unit, test-coverage]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
        - run: echo "im g"
  build:
    needs: [init, test-unit, test-coverage, lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build
  deploy:
    needs: [init, test-unit, test-coverage, lint]
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 Deployement"
  fin:
    needs: [init, test-unit, test-coverage, lint, build, deploy]
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 Le pipeline se termine ici"
